[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

; UART0 - Serial Monitor (GPIO3 RX, GPIO1 TX)
; UART1 - RS485 (GPIO16 RX, GPIO17 TX)

lib_deps =
    PubSubClient
    bblanchon/ArduinoJson @ ^6.19.0
    SPIFFS

board_build.partitions = default.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio

upload_protocol = esptool
monitor_port = COM6
upload_port = COM6

build_flags =
    -DCORE_DEBUG_LEVEL=0
